#!/bin/sh
ch_con_recursive() {
    dirs=$(echo $* | awk '{ print substr($0, index($0,$1)) }');
    for i in $dirs; do
        find "$i" -exec LD_LIBRARY_PATH=/system/lib /system/toolbox chcon u:object_r:system_file:s0 {} +;
        find "$i" -exec LD_LIBRARY_PATH=/system/lib /system/bin/toolbox chcon u:object_r:system_file:s0 {} +;
        find "$i" -exec chcon u:object_r:system_file:s0 {} +;
    done;
}

chmod 0755 /system/app
chmod -R 0644 /system/app/*

if [ -d "/system/priv-app" ];then
    chmod 0755 /system/priv-app
    chmod -R 0644 /system/priv-app/*
fi

chmod 0755 /system/framework
chmod -R 0644 /system/framework/*

chmod 0755 /system/lib
chmod -R 0644 /system/lib/*

chmod 0755 /system/tts
chmod -R 0644 /system/tts/*

chmod 0755 /system/usr/srec/en-US
chmod -R 0644 /system/usr/srec/en-US/*

chmod 0755 /system/etc/permissions
chmod -R 0644 /system/etc/permissions/*

chmod 0755 /system/etc/preferred-apps
chmod -R 0644 /system/etc/preferred-apps/*

chmod 0755 /system/vendor/pittpatt
chmod -R 0644 /system/vendor/pittpatt/*
busybox chown -R 0:2000 /system/vendor/pittpatt

chmod -R 0755 /system/addon.d
chmod -R 0755 /system/etc/sysconfig
chmod 0644 /system/etc/g.prop

ch_con_recursive "/system/app" "/system/framework" "/system/lib" "/system/priv-app" "/system/usr/srec/en-US" "/system/vendor/pittpatt" "/system/etc/permissions" "/system/etc/preferred-apps" "/system/addon.d" "/system/etc/sysconfig";
ch_con /system/etc/g.prop;
